# Generated by Django 4.2.1 on 2023-05-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField(blank=True, null=True)),
                ('Answer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
